[package]
name = "velocity_daw"
build = "src/build.rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.2.1"

[build-dependencies]
slint-build = "1.2.1"
